#ifndef CONFIG_H
#define CONFIG_H

/* Data update rates */
#define SDCARD_PACKET_DELAY_MS       100

#define MPU6050_CONVERSION_DELAY_MS  10
#define HMC5883L_CONVERSION_DELAY_MS 20
#define MADGWICK_UPDATE_DELAY_MS     10
#define BH1750_CONVERSION_DELAY_MS   400
#define ADC_CONVERSION_DELAY_MS      300
#define MLX90614_CONVERSION_DELAY_MS 500

#endif
